/* import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/master/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
 */
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faSearch} from '@fortawesome/free-solid-svg-icons'
import { Button } from 'react-bootstrap'
import Link from 'next/link'
import { useState } from 'react'


export default function Home() {
  const [see,Setsee] = useState(false);

const ChangeStateofSee =() =>{
  Setsee(true)
  setTimeout(() => {
    Setsee(false)
  }, 500);
}
  return (
      <div className="home_card">
        <div className="imagesearch">
            <div className="positionBar ">
              <div className="d-flex justify-content-center h-100">
                <div className="searchbar">
                  <input className="search_input"  /* value={SearchG} */
                    type="text" name="" 
                    placeholder="Search..."
                /*    onChange={e=>setSearchG(e.target.value.toLowerCase())} */
                  ></input>
                    {/*   <a href="/SearchResult" className="search_icon">
                        <FontAwesomeIcon icon={faSearch} type="submit" onChange={handlesubmit} />
                      </a> */}
                  <Link href="/Result" >
                    <button  className="search_icon">
                      <FontAwesomeIcon icon={faSearch} type="submit"  />
                    </button>
                  </Link>
                </div>
              </div>
            </div>
          </div>
        <div className="IndexCard">
                      <div className="Present">
                        <div className="bodyIndex">
                          test
                        </div>
                        <div className="IndexFooter">
                          <div className="infoIndex">
                          <button variant="warning" type="submit" /* className="buttonCard" */className={see ? "buttonCard activee " : "buttonCard"}  onClick={ChangeStateofSee}>
                            <div  className="iconSee">
                              <FontAwesomeIcon icon={faSearch }/>
                            </div>
                            <div className="textIndex">
                              <b>See</b>
                            </div>
                          </button>
                          </div>
                        </div>
                      </div>

                      <div className="Present">
                        <div className="bodyIndex">
                          test
                        </div>
                        <div className="IndexFooter">
                          <div className="infoIndex">
                          <button variant="warning" type="submit" /* className="buttonCard" */className={see ? "buttonCard activee " : "buttonCard"}  onClick={ChangeStateofSee}>
                            <div  className="iconSee">
                              <FontAwesomeIcon icon={faSearch }/>
                            </div>
                            <div className="textIndex">
                              <b>See</b>
                            </div>
                          </button>
                          </div>
                        </div>
                      </div>
                      <div className="Present">
                        <div className="bodyIndex">
                          test
                        </div>
                        <div className="IndexFooter">
                          <div className="infoIndex">
                          <button variant="warning" type="submit" /* className="buttonCard" */className={see ? "buttonCard activee " : "buttonCard"}  onClick={ChangeStateofSee}>
                            <div  className="iconSee">
                              <FontAwesomeIcon icon={faSearch }/>
                            </div>
                            <div className="textIndex">
                              <b>See</b>
                            </div>
                          </button>
                          </div>
                        </div>
                      </div>
                      <div className="Present">
                        <div className="bodyIndex">
                          test
                        </div>
                        <div className="IndexFooter">
                          <div className="infoIndex">
                          <button variant="warning" type="submit" /* className="buttonCard" */className={see ? "buttonCard activee " : "buttonCard"}  onClick={ChangeStateofSee}>
                            <div  className="iconSee">
                              <FontAwesomeIcon icon={faSearch }/>
                            </div>
                            <div className="textIndex">
                              <b>See</b>
                            </div>
                          </button>
                          </div>
                        </div>
                      </div>
                      <div className="Present">
                        <div className="bodyIndex">
                          test
                        </div>
                        <div className="IndexFooter">
                          <div className="infoIndex">
                          <button variant="warning" type="submit" /* className="buttonCard" */className={see ? "buttonCard activee " : "buttonCard"}  onClick={ChangeStateofSee}>
                            <div  className="iconSee">
                              <FontAwesomeIcon icon={faSearch }/>
                            </div>
                            <div className="textIndex">
                              <b>See</b>
                            </div>
                          </button>
                          </div>
                        </div>
                      </div>
        </div>
      
      
        
    </div>
  )
}
